image: maven:3-jdk-8

variables:
  # Use the cached directory above.
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

stages:
    - build
    - test
    
bulid:
    stage: build
    script: 
        - mvn $MAVEN_CLI_OPTS compile

    
    
test:
    stage: test
    script: 
        - echo test 1...
        - echo test 2...