image: maven:3-jdk-7

build:
  script: "mvn install -B"
  
stages:
  - compile
  - test
  - package

install_dependencies:
  stage: compile
  script:
    - maven compile 
    
test_with_lab:
  stage: test
  script: maven test
  
create_jar_file:
    stage: package
    script:
    - maven package