image: maven:3-jdk-8

variables:
  # Use the cached directory above.
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

stages:
    - build
    - test
    
bulid:
    stage: build
    script: "mvn clean install -DskipTests"
    
    
test:
    stage: test
    script: 
        - echo test 1...
        - echo test 2...